export { default as HeroComponent } from './HeroComponent';
export { default as ValuePropositionComponent } from './ValuePropositionComponent';
export { default as PersonalInfoComponent } from './PersonalInfoComponent';
export { default as ContactComponent } from './ContactComponent';
export { default as ExperienceComponent } from './ExperienceComponent';
export { default as EducationCertsComponent } from './EducationCertsComponent';
export { default as SkillsComponent } from './SkillsComponent';
export { default as ProjectsComponent } from './ProjectsComponent';
export { default as LanguagesComponent } from './LanguagesComponent';
